### ISSUE TITLE
Add in images in Prebuilt Dialogs

### ISSUE THREAD

**Issue by dariofinotti** [shunkosa/einstein-bots-ui-recipe#12]
Hi,
Is there a chance to add in image also in Prebuilt Dialogs ?
Thanks.
Dario

**Comment by shunkosa** [comment]
@dariofinotti Thank you for the comment! Can you please elaborate "Prebuilt Dialogs"?

**Comment by dariofinotti** [comment]
Hi shukosa, these ones are prebuilt dialogs: https://trailhead.salesforce.com/en/content/learn/projects/build-an-einstein-bot/add-prebuilt-dialogs-and-customize-the-options-menu
thanks

**Comment by shunkosa** [comment]
@dariofinotti Ah, so you want to add images in button menu?

**Comment by dariofinotti** [comment]
yes, it is and give possibility to slide images to choose che correct one, like choice responses

**Comment by shunkosa** [comment]
@dariofinotti Unfortunately, `lightningspanin-base-chat` only supports message UI.
https://developer.salesforce.com/docs/component-library/bundle/lightningsnapin-base-chat-message/documentation
Hope salesforce will provide the mechanism for the future!
