### ISSUE TITLE
Issue with RICH_TEXT on iOS

### ISSUE THREAD

**Issue by fabienseneca** [shunkosa/einstein-bots-ui-recipe#16]
Hi Shun Kosaka,
Thanks for sharing your code for this chatMessage LWC.
I have played with it and especially with RICH_TEXT that is well working on Web, Android App but not iOS App.
On iOS, we can see the html tag: they are not interpreted
![image (15)](https://user-images.githubusercontent.com/42960886/165093901-cb3b0ffb-d6d2-4f97-8c48-26df37b7eee9.png)

Do you have the same issue?
BR

Fabien

**Comment by shunkosa** [comment]
This component is expected to be used in web. I'm just surprised it's working in Android.

**Comment by fabienseneca** [comment]
Thanks for your answer @shunkosa !
have a great day
