### ISSUE TITLE
Image tag not showing properly

### ISSUE THREAD

**Issue by jbantequera** [shunkosa/einstein-bots-ui-recipe#4]
I made a dialog for testing every tag available and I don't know why but the Image one showed a broken file, I checked the url on the console and it was OK.

![image](https://user-images.githubusercontent.com/32770909/75455497-c472e380-5979-11ea-8f73-95b5e4d99d49.png)
![image](https://user-images.githubusercontent.com/32770909/75455517-c89f0100-5979-11ea-9c90-575666ea5f6d.png)

**Comment by shunkosa** [comment]
@jbantequera Thank you for the feedback! It seems working in my DE org. Are you trying in the bot preview pane or on a web page?
<img width="353" alt="screenshot" src="https://user-images.githubusercontent.com/1404346/75733297-437c6900-5d38-11ea-9812-efcfbd661c58.png">

**Comment by jbantequera** [comment]
It works on the preview of the einstein bot, but if I embed the chatbot on a community page via service chat it won't display anything :\

**Comment by jbantequera** [comment]
Nevermind, the problem was that the URL was not whitelisted in the CSP on my org, sorry!
