### ISSUE TITLE
Issue with the single quote and double quote

### ISSUE THREAD

**Issue by pirouzSZJ** [shunkosa/einstein-bots-ui-recipe#9]
for the customer messages (!isAgent) the single quotes and double quotes are being displayed as &#27; and &quot;

**Comment by shunkosa** [comment]
@pirouzSZJ Thanks for the reporting! Just update the agent message stye today. Can you check again with the latest code?

**Comment by shunkosa** [comment]
I'll close this issue because no updates. Please create another issue if it still happens.
